// Site-wide configuration
import webIcon from '../assets/homeAssets/web.svg';
import appIcon from '../assets/homeAssets/app.svg';
import uiuxIcon from '../assets/homeAssets/uiux.svg';
import aiIcon from '../assets/homeAssets/ai.svg';
import cloudIcon from '../assets/homeAssets/cloud.svg';
import saasIcon from '../assets/homeAssets/saas.svg';

export const siteConfig = {
  name: 'Encova Solutions',
  tagline: 'Transforming Ideas into Digital Excellence',
  description: 'Leading IT solutions and consulting company specializing in web development, mobile apps, UI/UX design, AI, and graphic design.',
  
  contact: {
    email: 'info@encovasolutions.com',
    phone: '+92 311 9093 230',
    address: 'Office No. TF 200, Deans Trade Center, Peshawar, Pakistan',
    mapLink: 'https://maps.google.com',
  },
  
  social: {
    linkedin: 'https://www.linkedin.com/company/encova-solutions-pvt-limited/',
    instagram: 'https://www.instagram.com/encovasolutions/',
    twitter: '#',
    facebook: '#',
  },
  
  services: [
    {
      id: 'web',
      name: 'Web Development',
      firstname: 'Web',
      secondname: 'Development',
      shortDesc: 'Custom web solutions built with cutting-edge technologies',
      description: "We create responsive, scalable, and high-performance web applications tailored to your business needs. From corporate websites to complex web platforms, our team delivers excellence.",
      icon: webIcon,
      features: ['Responsive web design for all devices', 'Progressive Web Applications (PWA)', 'Single Page Applications (SPA)', 'E-commerce platform development', 'Content Management Systems (CMS)', 'Custom web portals and dashboards', 'API integration and development', 'Performance optimization'],
      technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'PostgreSQL', 'TypeScript', 'AWS', 'GraphQL', 'Docker', 'Tailwind CSS', 'Redux', 'Express.js', 'REST APIs'],
    },
    {
      id: 'app',
      name: 'App Development',
      firstname: 'App',
      secondname: 'Development',
      shortDesc: 'Native and cross-platform mobile applications',
      description: 'Build powerful, feature-rich mobile applications for iOS and Android platforms. We create intuitive mobile experiences that engage users and drive business growth.',
      icon: appIcon,
      features: ['Native iOS and Android development', 'Cross-platform mobile apps', 'Mobile UI/UX Design', 'App Store and Play Store deployment', 'Push Notifications', 'Offline functionality', 'Location-based services', 'In-app purchases and subscriptions'],
      technologies: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase', 'REST APIs'],
    },
    {
      id: 'uiux',
      name: 'UI/UX Design',
      firstname: 'UI/UX ',
      secondname: 'Design',
      shortDesc: 'User-centered design that converts',
      description: 'Create stunning, user-centered designs that delight your customers and drive engagement. We combine beautiful aesthetics with intuitive functionality to deliver exceptional user experiences.',
      icon: uiuxIcon,
      features: ['User research and persona development', 'Information Architecture', 'Wireframing and prototyping', 'Visual design and branding', 'Interaction Design','Usability Testing', 'Design systems and style guides', 'Responsive and adaptive design'],
      technologies: ['Figma', 'Adobe XD', 'Sketch', 'InVision', 'Principle', 'Framer'],
    },
    {
      id: 'ai',
      name: 'AI Solutions',
      firstname: 'AI ',
      secondname: 'Solutions',
      shortDesc: 'Intelligent systems powered by machine learning',
      description: 'Build intelligent AI solutions that drive automation, advanced analytics, and data-driven decision-making, delivering scalable systems that adapt and create real business value.',
      icon: aiIcon,
      features: ['Machine Learning models', 'Predictive Analytics', 'Natural Language Processing','Computer Vision', 'Intelligent chatbots', 'AI process automation', 'Recommendation engines', 'Anomaly detection'],
      technologies: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI', 'Hugging Face', 'LangChain'],
    },
      {
      id: 'saas',
      name: 'Saas Development',
      firstname: 'Saas ',
      secondname: 'Development',
      shortDesc: 'Visual identity that tells your story',
      description: 'Build scalable, secure, and feature-rich Software-as-a-Service platforms. We develop end-to-end SaaS solutions with subscription management, multi-tenancy, and enterprise-grade features.',
      icon: saasIcon,
      features: ['Multi-tenant architecture', 'Subscription and billing management', 'Role-based access control (RPAC)', 'Analytics and reporting dashboards', 'API development and documentation', 'Scalable cloud infrastructure', 'Data security and encryption', 'Third-party integrations'],
      technologies: ['React.js', 'Next.js', 'Node.js', 'PostgreSQL', 'Stripe', 'AWS', 'Docker', 'Kubernetes', 'Redis', 'GraphQL', 'Typescript', 'Microservices'],
    },
    {
      id: 'cloud',
      name: 'Cloud & Devops ',
       firstname: 'Cloud &',
      secondname: 'Devops',
      shortDesc: 'Visual identity that tells your story',
      description: 'Architected and maintained cloud-native environments on AWS, Azure, and GCP with fully automated CI/CD pipelines, enabling faster releases, high availability, and operational efficiency.',
      icon: cloudIcon,
      features: ['Cloud infrastructure setup and management', 'CI/CD pipeline configuration', 'CI/CD pipeline configuration', 'Infrastructure as Code (IaC)', 'Monitoring and logging solutions', 'Auto-scaling and load balancing','Security implementation & audits','Disaster recovery planning'],
      technologies: ['AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'Ansible', 'Jenkins', 'Prometheus', 'Grafana', 'Gitlab CI/CD', 'ELK Stack'],
    },
     
  ],
  
  portfolio: [
    {
      id: 1,
      title: 'Gym Management System',
      category: 'web',
      description: 'Designed full-stack gym management system automating operations like member management, subscriptions, attendance and payments.',
      image: '/GMS.jpeg',
      technologies: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    },
    {
      id: 2,  
      title: 'JKD Pakistan',
      category: 'web',
      description: 'Developed responsive website for JKD Pakistan enhancing digital presence by implementing Modern UI, fast performance, clear navigation',
      image: '/JKD.png',
      technologies: ['React', 'Node.js', 'Express', "MongoDB"],
    },
    {
      id: 3,
      title: 'Exodus',
      category: 'uiux',
      description: 'Crafted intuitive UI/UX design for Exodus gaming web and app focusing on user-friendly navigation, modern aesthetics, and seamless experience.',
      image: '/Exodus.png',
      technologies: ['Figma', 'Adobe XD', 'Principle'],
    },
    // {
    //   id: 4,
    //   title: 'Avicenna Enterprises Solutions',
    //   category: 'web',
    //   description: 'Built responsive corporate website showcasing IT AI services with modern design and seamless user experience.',
    //   image: '/Avicenna.png',
    //   technologies: ['Python', 'OpenAI', 'LangChain', 'FastAPI'],
    // },
    {
      id: 4,
      title: 'Study Studio',
      // category: 'graphics',
            category: 'web',

      description: 'Developed frontend for AI-powered personalized study platform offering tailored learning resources and progress tracking.',
      image: '/StudyStudio.png',
      technologies: ['React', 'Node.js', 'Express', "MongoDB"],
    },
    {
      id: 5,
      title: 'AI Tool Finder',
      category: 'ai',
      description: 'Full-Stack Engineer building AI tool discovery platform with AI research, comparison, recommendations and workflow integration',
      image: '/AIToolFinder.png',
      technologies: ['Next.js', 'PostgreSQL', 'AWS', 'Mapbox'],
    },
  ],
  
  testimonials: [
    {
      id: 1,
      name: 'Abdul Basit',
      position: 'CEO, Encova Solutions',
      content: 'Encova Solutions transformed our vision into reality. Their team delivered a stunning website that exceeded our expectations and significantly improved our online presence.',
      rating: 5,
      avatar: '/images/testimonials/avatar1.jpg',
    },
    {
      id: 2,
      name: 'Talha Ahmad Awan ',
      position: 'Founder, Encova Solutions',
      content: 'Working with Encova was a game-changer for our startup. They developed our mobile app with precision and creativity, resulting in a 200% increase in user engagement.',
      rating: 5,
      avatar: '/images/testimonials/avatar2.jpg',
    },
    {
      id: 3,
      name: 'Abdul Samad',
      position: 'Full stack Developer, Encova Solutions',
      content: 'Full-stack developer committed to code excellence',
      rating: 5,
      avatar: '/images/testimonials/avatar3.jpg',
    },
    {
      id: 4,
      name: 'Muhammad Khanzala',
      position: 'MERN Stack Developer, Encova Solutions',
      content: 'Skilled developer focused on building efficient web applications.',
      rating: 5,
      avatar: '/images/testimonials/avatar4.jpg',
    },
  ],
  
  team: [
    {
      id: 1,
      name: 'Abdul Basit',
      position: 'CEO & Founder',
      bio: 'Visionary leader with 3+ years in Tech Industry',
      image: './ceo.png',
      social: { linkedin: 'https://www.linkedin.com/in/abdul-basit-1039b522b',},
    },
    {
      id: 2,
      name: 'Talha Ahmad',
      position: 'CO-founder',
      bio: 'Technology expert specializing in scalable architectures',
      image: './talha.png',
      social: { linkedin: 'https://www.linkedin.com/in/talhan-ahmad' },
    },
    {
      id: 3,
      name: 'Abdul Samad',
      position: 'Senior Web Developer',
      bio: 'Full-stack developer committed to code excellence',
      image: './samad.png',
      social: { linkedin: 'https://www.linkedin.com/in/abdul-samad-912882284/'},
    },
       {
      id: 4,
      name: 'Rehmat Ullah',
      position: 'UI/UX Designer',
      bio: 'Designer focused on intuitive, user-centered experiences.',
      image: './Rehmat.png',
      social: { linkedin: 'https://www.linkedin.com/in/rahmat-u-9a63b1243/'},
    },
    {
      id: 5,
      name: 'M. Hanzala Khan',
      position: 'MERN Stack Developer',
      bio: 'Skilled developer focused on building efficient web applications',
      image: './hanzala.png',
      social: { linkedin: 'https://www.linkedin.com/in/mhk47/'},
    },
  
  ],
  
  careers: [
    {
      id: 1,
      title: 'Associate Software Engineer',
      type: 'Full-time',
      experience: 'Minimum 1 year',
      stack: 'MERN Stack',
      description: 'We are looking for a talented software engineer with experience in MongoDB, Express, React, and Node.js to join our development team.',
      requirements: [
        '1+ years of experience with MERN stack',
        'Strong understanding of JavaScript/ES6+',
        'Experience with RESTful APIs',
        'Knowledge of Git and version control',
        'Good problem-solving skills',
      ],
    },
    {
      id: 2,
      title: 'UI/UX Developer',
      type: 'Full-time',
      experience: '1 year',
      stack: 'Figma, Adobe XD, React',
      description: 'Join our design team to create beautiful and functional user interfaces that delight our clients and their users.',
      requirements: [
        '1+ year of UI/UX design experience',
        'Proficiency in Figma and Adobe XD',
        'Understanding of React components',
        'Strong portfolio demonstrating design skills',
        'Knowledge of responsive design principles',
      ],
    },
    {
      id: 3,
      title: 'MERN Stack Intern',
      type: 'Internship',
      experience: 'Fresh/Student',
      stack: 'MERN Stack',
      description: 'Perfect opportunity for students or fresh graduates to learn and grow with hands-on experience in full-stack development.',
      requirements: [
        'Basic knowledge of JavaScript',
        'Familiarity with React',
        'Eagerness to learn',
        'Good communication skills',
        'Available for 3-6 months',
      ],
    },
    {
      id: 4,
      title: 'UI/UX Design Intern',
      type: 'Internship',
      experience: 'Fresh/Student',
      stack: 'Figma, Adobe XD',
      description: 'Learn from experienced designers and work on real projects while developing your design skills.',
      requirements: [
        'Basic understanding of design principles',
        'Familiarity with Figma or Adobe XD',
        'Creative mindset',
        'Portfolio or design samples',
        'Available for 3-6 months',
      ],
    },
    {
      id: 5,
      title: 'Graphic Design Intern',
      type: 'Internship',
      experience: 'Fresh/Student',
      stack: 'Adobe Suite',
      description: 'Work on diverse graphic design projects including branding, marketing materials, and digital assets.',
      requirements: [
        'Knowledge of Adobe Illustrator and Photoshop',
        'Understanding of color theory and typography',
        'Creative portfolio',
        'Attention to detail',
        'Available for 3-6 months',
      ],
    },
    {
      id: 6,
      title: 'Front-end Developer Intern',
      type: 'Internship',
      experience: 'Fresh/Student',
      stack: 'React.js',
      description: 'Build modern web applications using React and learn industry best practices from senior developers.',
      requirements: [
        'Basic knowledge of HTML, CSS, JavaScript',
        'Familiarity with React.js',
        'Understanding of responsive design',
        'Problem-solving skills',
        'Available for 3-6 months',
      ],
    },
  ],
  
  howWeWork: [
    {
      step: 1,
      title: 'Discussion and Analysis',
      description: 'We begin by understanding your business goals, target audience, and project requirements through detailed consultations.',
      objectives: [
        'Understand client requirements',
        'Identify project scope',
        'Define success metrics',
        'Assess technical feasibility',
      ],
      deliverables: [
        'Requirements document',
        'Project proposal',
        'Timeline and budget estimate',
      ],
      team: ['Project Manager', 'Business Analyst', 'Technical Lead'],
      icon: '💬',
    },
    {
      step: 2,
      title: 'Planning and Design',
      description: 'Strategic planning and architectural design to create a solid foundation for your project.',
      objectives: [
        'Create project roadmap',
        'Define system architecture',
        'Plan resource allocation',
        'Establish milestones',
      ],
      deliverables: [
        'Project plan',
        'System architecture diagram',
        'Resource allocation plan',
        'Risk assessment',
      ],
      team: ['Project Manager', 'Solution Architect', 'UI/UX Designer'],
      icon: '📋',
    },
    {
      step: 3,
      title: 'Software Design',
      description: 'Creating intuitive and visually appealing designs that align with your brand and user needs.',
      objectives: [
        'Design user interface',
        'Create user experience flow',
        'Develop design system',
        'Ensure brand consistency',
      ],
      deliverables: [
        'Wireframes',
        'High-fidelity mockups',
        'Interactive prototypes',
        'Design specifications',
      ],
      team: ['UI/UX Designer', 'Graphic Designer', 'Creative Director'],
      icon: '🎨',
    },
    {
      step: 4,
      title: 'Software Development',
      description: 'Building robust and scalable solutions using modern technologies and best practices.',
      objectives: [
        'Implement features',
        'Write clean code',
        'Integrate APIs',
        'Optimize performance',
      ],
      deliverables: [
        'Working software',
        'Source code',
        'Technical documentation',
        'API documentation',
      ],
      team: ['Frontend Developers', 'Backend Developers', 'DevOps Engineer'],
      icon: '💻',
    },
    {
      step: 5,
      title: 'Quality Assurance',
      description: 'Rigorous testing to ensure your product is bug-free, secure, and performs optimally.',
      objectives: [
        'Identify and fix bugs',
        'Ensure security',
        'Test across devices',
        'Validate functionality',
      ],
      deliverables: [
        'Test reports',
        'Bug fixes',
        'Performance optimization',
        'Security audit',
      ],
      team: ['QA Engineers', 'Security Specialist', 'Performance Analyst'],
      icon: '🔍',
    },
    {
      step: 6,
      title: 'Maintenance',
      description: 'Ongoing support and updates to keep your solution running smoothly and up-to-date.',
      objectives: [
        'Monitor system health',
        'Provide technical support',
        'Implement updates',
        'Ensure scalability',
      ],
      deliverables: [
        'Regular updates',
        'Performance reports',
        'Bug fixes',
        'Feature enhancements',
      ],
      team: ['Support Team', 'DevOps Engineer', 'System Administrator'],
      icon: '🔧',
    },
  ],
};

export default siteConfig;

